# Generated by Django 6.0.2 on 2026-03-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_bio_alter_profile_role_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMINISTRADOR', 'admin'), ('RH', 'Recursos Humanos'), ('GESTOR', 'Manager')], default='RH', max_length=20),
        ),
    ]
