# Generated by Django 6.0.2 on 2026-03-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome do Perfil')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('permissions', models.JSONField(blank=True, null=True, verbose_name='Permissões')),
                ('is_system', models.BooleanField(default=False, verbose_name='Perfil do Sistema')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Perfil de Acesso',
                'verbose_name_plural': 'Perfis de Acesso',
                'ordering': ['name'],
            },
        ),
    ]
