# Generated by Django 6.0.2 on 2026-03-31 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão'), ('VIEW', 'Visualização'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Exportação'), ('IMPORT', 'Importação'), ('APPROVE', 'Aprovação'), ('REJECT', 'Rejeição')], max_length=20, verbose_name='Tipo de Ação')),
                ('table_name', models.CharField(help_text='Nome do modelo/tabela afetado', max_length=100, verbose_name='Nome da Tabela')),
                ('record_id', models.IntegerField(blank=True, help_text='ID do registro afetado (NULL para ações como login)', null=True, verbose_name='ID do Registro')),
                ('old_data', models.JSONField(blank=True, help_text='Snapshot dos dados antes da alteração', null=True, verbose_name='Dados Anteriores')),
                ('new_data', models.JSONField(blank=True, help_text='Snapshot dos dados após a alteração', null=True, verbose_name='Dados Novos')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP do usuário que realizou a ação', null=True, verbose_name='Endereço IP')),
                ('user_agent', models.CharField(blank=True, help_text='Informações do navegador/dispositivo', max_length=500, null=True, verbose_name='User Agent')),
                ('session_id', models.CharField(blank=True, help_text='Identificador da sessão do usuário', max_length=100, null=True, verbose_name='ID da Sessão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('user', models.ForeignKey(blank=True, help_text='Usuário que realizou a ação (NULL para ações anônimas)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-created_at'],
                'permissions': [('can_view_audit_logs', 'Pode visualizar logs de auditoria'), ('can_export_audit_logs', 'Pode exportar logs de auditoria')],
                'indexes': [models.Index(fields=['user'], name='idx_auditlog_user'), models.Index(fields=['table_name'], name='idx_auditlog_table'), models.Index(fields=['action_type'], name='idx_auditlog_action'), models.Index(fields=['created_at'], name='idx_auditlog_created_at'), models.Index(fields=['table_name', 'record_id'], name='idx_auditlog_table_record'), models.Index(fields=['action_type', 'created_at'], name='idx_auditlog_action_date')],
            },
        ),
    ]
