# Generated by Django 6.0.2 on 2026-03-31 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('VACATION', 'Férias'), ('SICK_LEAVE', 'Atestado Médico'), ('PERSONAL', 'Assuntos Pessoais'), ('MATERNITY', 'Licença Maternidade'), ('PATERNITY', 'Licença Paternidade'), ('BEREAVEMENT', 'Luto'), ('UNPAID', 'Licença Não Remunerada'), ('OTHER', 'Outros')], max_length=50, verbose_name='Tipo de Ausência')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(verbose_name='Data de Término')),
                ('days_requested', models.IntegerField(verbose_name='Dias Solicitados')),
                ('reason', models.TextField(blank=True, help_text='Justificativa para a solicitação (obrigatório para alguns tipos)', null=True, verbose_name='Motivo')),
                ('attachment', models.CharField(blank=True, help_text='Caminho do arquivo anexado (ex: atestado médico)', max_length=500, null=True, verbose_name='Anexo')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Status')),
                ('rejection_reason', models.TextField(blank=True, help_text='Preenchido quando a solicitação é rejeitada', null=True, verbose_name='Motivo da Rejeição')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employee.employee', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Solicitação de Ausência',
                'verbose_name_plural': 'Solicitações de Ausência',
                'ordering': ['-created_at'],
                'permissions': [('can_approve_leaverequest', 'Pode aprovar solicitações de ausência'), ('can_view_all_leaverequests', 'Pode visualizar todas as solicitações')],
                'indexes': [models.Index(fields=['employee'], name='idx_leaverequest_employee'), models.Index(fields=['status'], name='idx_leaverequest_status'), models.Index(fields=['start_date', 'end_date'], name='idx_leaverequest_dates'), models.Index(fields=['leave_type'], name='idx_leaverequest_type'), models.Index(fields=['created_at'], name='idx_leaverequest_created'), models.Index(fields=['employee', 'status'], name='idx_leaverequest_emp_status')],
            },
        ),
    ]
