# Generated by Django 6.0.2 on 2026-03-30 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Cargo')),
                ('level', models.CharField(blank=True, choices=[('TRAINEE', 'Trainee'), ('JUNIOR', 'Júnior'), ('PLENO', 'Pleno'), ('SENIOR', 'Sênior'), ('SPECIALIST', 'Especialista'), ('MANAGER', 'Gerente'), ('DIRECTOR', 'Diretor')], max_length=20, null=True, verbose_name='Nível')),
                ('min_wage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salário Mínimo')),
                ('max_wage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salário Máximo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='department.department', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['name'],
            },
        ),
    ]
