# Generated by Django 6.0.2 on 2026-03-31 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CONTRACT', 'Contrato'), ('CERTIFICATE', 'Certificado'), ('IDENTITY', 'Documento de Identidade'), ('RESUME', 'Currículo'), ('MEDICAL', 'Documento Médico'), ('OTHER', 'Outros')], max_length=50, verbose_name='Tipo de Documento')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Documento')),
                ('file_path', models.CharField(max_length=500, verbose_name='Caminho do Arquivo')),
                ('file_type', models.CharField(help_text='Ex: PDF, DOC, JPEG', max_length=50, verbose_name='Tipo de Arquivo')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='Tamanho do Arquivo (bytes)')),
                ('expiration_date', models.DateField(blank=True, help_text='Preencher se o documento tem validade', null=True, verbose_name='Data de Validade')),
                ('is_active', models.BooleanField(default=True, help_text='Documentos inativos não são considerados em validações', verbose_name='Ativo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employee.employee', verbose_name='Funcionário')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-uploaded_at', 'employee', 'document_type'],
                'indexes': [models.Index(fields=['employee'], name='idx_document_employee'), models.Index(fields=['document_type'], name='idx_document_type'), models.Index(fields=['expiration_date'], name='idx_document_expiration'), models.Index(fields=['is_active'], name='idx_document_active'), models.Index(fields=['employee', 'is_active'], name='idx_document_employee_active')],
            },
        ),
    ]
