# Generated by Django 6.0.2 on 2026-03-30 12:54

import django.db.models.deletion
import employee.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('position', '0001_initial'),
        ('status', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Primeiro Nome')),
                ('last_name', models.CharField(max_length=150, verbose_name='Sobrenome')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[employee.models.validate_cpf], verbose_name='CPF')),
                ('personal_email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail Pessoal')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail Corporativo')),
                ('birth_date', models.DateField(help_text='Formato: DD/MM/AAAA', verbose_name='Data de Nascimento')),
                ('hire_date', models.DateField(help_text='Formato: DD/MM/AAAA', verbose_name='Data de Admissão')),
                ('wage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário')),
                ('emergency_contact', models.CharField(blank=True, max_length=150, null=True, verbose_name='Contato de Emergência')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone de Emergência')),
                ('resignation_date', models.DateField(blank=True, help_text='Formato: DD/MM/AAAA', null=True, verbose_name='Data de Desligamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.address', verbose_name='Endereço')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='position.position', verbose_name='Cargo')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='status.status', verbose_name='Status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
