# Generated by Django 6.0.2 on 2026-03-31 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0002_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_percentage', models.DecimalField(decimal_places=2, default=100.0, help_text='Percentual de dedicação ao departamento (0-100%)', max_digits=5, verbose_name='Percentual de Alocação')),
                ('is_primary', models.BooleanField(default=False, help_text='Indica se este é o departamento principal do funcionário', verbose_name='Departamento Principal')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, help_text='Preencher quando a alocação for encerrada', null=True, verbose_name='Data de Término')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='department.department', verbose_name='Departamento')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_assignments', to='employee.employee', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Alocação de Funcionário',
                'verbose_name_plural': 'Alocações de Funcionários',
                'ordering': ['employee', '-is_primary', 'start_date'],
                'indexes': [models.Index(fields=['employee'], name='idx_emp_dept_employee'), models.Index(fields=['department'], name='idx_emp_dept_department'), models.Index(fields=['is_primary'], name='idx_emp_dept_primary'), models.Index(fields=['end_date'], name='idx_emp_dept_end_date')],
                'unique_together': {('employee', 'department')},
            },
        ),
    ]
